// apps/core/spa/src/App.tsx
import { createSignal, onCleanup, onMount, Show } from 'solid-js'
import { Menu } from '@ark-ui/solid/menu'
import {
  Alert,
  Button,
  Card,
  FormField,
  Input,
  KeymapProvider,
  Layout,
  LayoutMain,
  LayoutMenu,
  Page,
  getTheme,
  getThemeMode,
  setI18nLocale,
  syncDocumentLocale,
  t,
  themeIconHref,
  navigateApp,
  menuContentClass,
  menuItemClass,
  type ThemeId,
} from '@kaizengo/sdk-solid/ui'
import type { NavEntry } from './lib/nav'
import { ViewHost } from './lib/ViewHost'
import { fetchMe, logout, type AuthUser } from './lib/auth'
import { Login } from './views/Login'

function currentAppRoute(): string {
  const path = window.location.pathname.replace(/\/+$/, '')
  const m = path.match(/^\/app\/([^/]+)/)
  return m?.[1] ?? ''
}

export default function App() {
  const [i18nReady, setI18nReady] = createSignal(false)
  const [apps, setApps] = createSignal<NavEntry[]>([])
  const [appRoute, setAppRoute] = createSignal(currentAppRoute())
  const [error, setError] = createSignal('')
  const [shellTitle, setShellTitle] = createSignal('KaizenGo')
  const [theme, setThemeState] = createSignal<ThemeId>(getTheme())
  const [user, setUser] = createSignal<AuthUser | null>(null)
  const [authLoading, setAuthLoading] = createSignal(true)
  const [appsMenuOpen, setAppsMenuOpen] = createSignal(false)

  const brandIcon = () => themeIconHref(getThemeMode(theme()))
  const activeEntry = () => apps().find((a) => a.route === appRoute())

  function syncRoute() {
    setAppRoute(currentAppRoute())
  }

  function navigate(to: string) {
    navigateApp(to ? `/app/${to}` : '/app/')
  }

  async function loadApps() {
    const res = await fetch('/api/apps', { credentials: 'include' })
    if (!res.ok) throw new Error(`Failed to load apps (${res.status})`)
    setApps(await res.json())
  }

  async function checkAuth() {
    setAuthLoading(true)
    try {
      const me = await fetchMe()
      setUser(me)
      if (me) {
        const { locale } = await syncDocumentLocale()
        setI18nLocale(locale)
        await loadApps()
      }
    } catch (e) {
      setUser(null)
      setError(e instanceof Error ? e.message : String(e))
    } finally {
      setAuthLoading(false)
    }
  }

  async function handleLogout() {
    await logout()
    setUser(null)
    setApps([])
    navigate('')
  }

  onMount(() => {
    const onPop = () => syncRoute()
    const onSettings = (e: Event) => {
      const detail = (e as CustomEvent<{ shellTitle?: string; locale?: string }>).detail
      if (detail?.shellTitle) setShellTitle(String(detail.shellTitle))
      if (detail?.locale) setI18nLocale(detail.locale)
      void loadApps()
    }
    const onTheme = (e: Event) => {
      const id = (e as CustomEvent<{ theme?: ThemeId }>).detail?.theme
      setThemeState(id ?? getTheme())
    }
    const onApps = () => {
      void loadApps()
    }
    const onToggleApps = () => setAppsMenuOpen(true)
    const onSignOut = () => {
      void handleLogout()
    }

    window.addEventListener('popstate', onPop)
    window.addEventListener('kaizengo:settings', onSettings)
    window.addEventListener('kaizengo:theme', onTheme)
    window.addEventListener('kaizengo:apps', onApps)
    window.addEventListener('kaizengo:shell.toggleApps', onToggleApps)
    window.addEventListener('kaizengo:shell.signOut', onSignOut)

    void (async () => {
      try {
        const { locale } = await syncDocumentLocale()
        setI18nLocale(locale)
      } finally {
        setI18nReady(true)
      }
      await checkAuth()
    })()

    onCleanup(() => {
      window.removeEventListener('popstate', onPop)
      window.removeEventListener('kaizengo:settings', onSettings)
      window.removeEventListener('kaizengo:theme', onTheme)
      window.removeEventListener('kaizengo:apps', onApps)
      window.removeEventListener('kaizengo:shell.toggleApps', onToggleApps)
      window.removeEventListener('kaizengo:shell.signOut', onSignOut)
    })
  })

  return (
    <Show
      when={i18nReady() && !authLoading()}
      fallback={
        <main class="auth-loading">
          <p>{t('shell.loading')}</p>
        </main>
      }
    >
      <Show when={user()} fallback={<Login onlogin={() => void checkAuth()} />}>
        {(currentUser) => (
          <KeymapProvider>
          <Page>
            <header class="shell-bar">
              <a
                class="brand"
                href="/app/"
                data-keymap-id="go-home"
                onClick={(e) => {
                  e.preventDefault()
                  navigate('')
                }}
              >
                <img src={brandIcon()} alt="KaizenGo" class="brand-icon" />
                <span class="brand-text">{shellTitle()}</span>
              </a>

              <Menu.Root
                open={appsMenuOpen()}
                onOpenChange={(e) => setAppsMenuOpen(e.open)}
                positioning={{ placement: 'bottom-start' }}
              >
                <Menu.Trigger
                  class="inline-flex h-8 items-center gap-2 border-0 bg-transparent px-4 text-sm text-[var(--kg-shell-text)] hover:bg-[var(--kg-shell-hover)]"
                  data-keymap-id="toggle-apps"
                >
                  {t('shell.apps')}
                  <span class="text-xs opacity-85">▾</span>
                </Menu.Trigger>
                <Menu.Positioner>
                  <Menu.Content class={menuContentClass}>
                    <Menu.Item
                      value="home"
                      class={menuItemClass}
                      onSelect={() => navigate('')}
                    >
                      {t('shell.home')}
                    </Menu.Item>
                    {apps().map((a) => (
                      <Menu.Item
                        value={a.route}
                        class={menuItemClass}
                        onSelect={() => navigate(a.route)}
                      >
                        {a.title}
                      </Menu.Item>
                    ))}
                    <Show when={!apps().length}>
                      <div class="px-4 py-3 text-sm text-[var(--kg-text-muted)]">{t('shell.no_apps')}</div>
                    </Show>
                  </Menu.Content>
                </Menu.Positioner>
              </Menu.Root>

              <div class="user-menu">
                <span class="user-name">{currentUser().name}</span>
                <Show when={currentUser().roles.includes('admin')}>
                  <span class="admin-badge">{t('shell.admin')}</span>
                </Show>
                <button type="button" class="logout-btn" data-keymap-id="sign-out" onClick={() => void handleLogout()}>
                  {t('shell.sign_out')}
                </button>
              </div>
            </header>

            <div class="shell-body">
              <Show
                when={appRoute()}
                fallback={
                  <Layout title={t('shell.welcome', currentUser().name)} subtitle={t('shell.signed_in', currentUser().email)}>
                    <LayoutMain>
                      <Card title={t('shell.get_started')}>
                        <p class="hint">{t('shell.get_started_hint')}</p>
                      </Card>
                    </LayoutMain>
                  </Layout>
                }
              >
                <Show
                  when={activeEntry()}
                  fallback={
                    <Layout title={t('shell.apps')}>
                      <LayoutMain>
                        <Alert variant="danger">{t('shell.no_apps')}</Alert>
                      </LayoutMain>
                    </Layout>
                  }
                >
                  {(entry) => (
                    <Show when={appRoute()} keyed>
                      {(route) => (
                        <Layout title={entry().title}>
                          <LayoutMenu app={route} />
                          <LayoutMain>
                            <Show when={error()}>
                              <Alert variant="danger">{error()}</Alert>
                            </Show>
                            <ViewHost hostApp={route} onerror={(message) => setError(message)} />
                          </LayoutMain>
                        </Layout>
                      )}
                    </Show>
                  )}
                </Show>
              </Show>
            </div>
          </Page>
          </KeymapProvider>
        )}
      </Show>
    </Show>
  )
}

// apps/core/spa/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import {
    Alert,
    Card,
    Layout,
    LayoutMain,
    LayoutMenu,
    Page,
    getTheme,
    getThemeMode,
    setI18nLocale,
    syncDocumentLocale,
    t,
    themeIconHref,
  } from '@kaizengo/sdk-svelte/ui'
  import type { ThemeId } from '@kaizengo/sdk-svelte/ui'
  import type { NavEntry } from './lib/nav'
  import ViewHost from './lib/ViewHost.svelte'
  import { fetchMe, logout, type AuthUser } from './lib/auth'
  import Login from './views/Login.svelte'

  let i18nReady = $state(false)
  let apps = $state<NavEntry[]>([])
  let appRoute = $state(currentAppRoute())
  let error = $state('')
  let menuOpen = $state(false)
  let shellTitle = $state('KaizenGo')
  let theme = $state<ThemeId>(getTheme())
  let brandIcon = $derived(themeIconHref(getThemeMode(theme)))
  let user = $state<AuthUser | null>(null)
  let authLoading = $state(true)

  const activeEntry = $derived(apps.find((a) => a.route === appRoute))

  function currentAppRoute(): string {
    const path = window.location.pathname.replace(/\/+$/, '')
    const m = path.match(/^\/app\/([^/]+)/)
    return m?.[1] ?? ''
  }

  function syncRoute() {
    appRoute = currentAppRoute()
  }

  function navigate(to: string) {
    const url = to ? `/app/${to}` : '/app/'
    history.pushState({}, '', url)
    syncRoute()
    menuOpen = false
  }

  async function checkAuth() {
    authLoading = true
    try {
      user = await fetchMe()
      if (user) {
        const { locale } = await syncDocumentLocale()
        setI18nLocale(locale)
        await loadApps()
      }
    } catch (e) {
      user = null
      error = e instanceof Error ? e.message : String(e)
    } finally {
      authLoading = false
    }
  }

  async function loadApps() {
    const res = await fetch('/api/apps', { credentials: 'include' })
    if (!res.ok) throw new Error(`Failed to load apps (${res.status})`)
    apps = await res.json()
  }

  async function handleLogout() {
    await logout()
    user = null
    apps = []
    navigate('')
  }

  onMount(() => {
    const onPop = () => {
      syncRoute()
    }
    const onSettings = (e: Event) => {
      const detail = (e as CustomEvent<{ shellTitle?: string; locale?: string; dir?: 'ltr' | 'rtl' }>)
        .detail
      if (detail?.shellTitle) shellTitle = String(detail.shellTitle)
      if (detail?.locale) {
        setI18nLocale(detail.locale)
      }
      void loadApps()
    }
    const onTheme = (e: Event) => {
      const id = (e as CustomEvent<{ theme?: ThemeId }>).detail?.theme
      theme = id ?? getTheme()
    }
    const onApps = () => {
      void loadApps()
    }
    window.addEventListener('popstate', onPop)
    window.addEventListener('kaizengo:settings', onSettings)
    window.addEventListener('kaizengo:theme', onTheme)
    window.addEventListener('kaizengo:apps', onApps)
    void (async () => {
      try {
        const { locale } = await syncDocumentLocale()
        setI18nLocale(locale)
      } finally {
        i18nReady = true
      }
      await checkAuth()
    })()
    return () => {
      window.removeEventListener('popstate', onPop)
      window.removeEventListener('kaizengo:settings', onSettings)
      window.removeEventListener('kaizengo:theme', onTheme)
      window.removeEventListener('kaizengo:apps', onApps)
    }
  })
</script>

{#if !i18nReady || authLoading}
  <main class="auth-loading"><p>{t('shell.loading')}</p></main>
{:else if !user}
  <Login {t} onlogin={() => void checkAuth()} />
{:else}
  <Page>
    <header class="shell-bar">
      <a
        class="brand"
        href="/app/"
        onclick={(e) => {
          e.preventDefault()
          navigate('')
        }}>
        <img src={brandIcon} alt="KaizenGo" class="brand-icon" />
        <span class="brand-text">{shellTitle}</span>
        </a
      >

      <div class="menu">
        <button
          type="button"
          class="menu-btn"
          aria-haspopup="listbox"
          aria-expanded={menuOpen}
          onclick={() => (menuOpen = !menuOpen)}
        >
          {t('shell.apps')}
          <span class="caret">▾</span>
        </button>
        {#if menuOpen}
          <ul class="menu-list" role="listbox">
            <li>
              <button type="button" class:active={appRoute === ''} onclick={() => navigate('')}>
                {t('shell.home')}
              </button>
            </li>
            {#each apps as a}
              <li>
                <button
                  type="button"
                  class:active={a.route === appRoute}
                  onclick={() => navigate(a.route)}
                >
                  {a.title}
                </button>
              </li>
            {/each}
            {#if !apps.length}
              <li class="empty">{t('shell.no_apps')}</li>
            {/if}
          </ul>
        {/if}
      </div>

      <div class="user-menu">
        <span class="user-name">{user.name}</span>
        {#if user.roles.includes('admin')}
          <span class="admin-badge">{t('shell.admin')}</span>
        {/if}
        <button type="button" class="logout-btn" onclick={() => void handleLogout()}>{t('shell.sign_out')}</button>
      </div>
    </header>

    <div class="shell-body">
      {#if appRoute === ''}
        <Layout title={t('shell.welcome', user.name)} subtitle={t('shell.signed_in', user.email)}>
          <LayoutMain>
            <Card title={t('shell.get_started')}>
              <p class="hint">{t('shell.get_started_hint')}</p>
            </Card>
          </LayoutMain>
        </Layout>
      {:else if activeEntry}
        {#key appRoute}
          <Layout title={activeEntry.title}>
            <LayoutMenu app={appRoute} />
            <LayoutMain>
              {#if error}
                <Alert variant="danger">{error}</Alert>
              {/if}
              <ViewHost
                hostApp={appRoute}
                onerror={(message) => (error = message)}
              />
            </LayoutMain>
          </Layout>
        {/key}
      {:else}
        <Layout title={t('shell.apps')}>
          <LayoutMain>
            <Alert variant="danger">{t('shell.no_apps')}</Alert>
          </LayoutMain>
        </Layout>
      {/if}
    </div>
  </Page>

  {#if menuOpen}
    <button
      type="button"
      class="backdrop"
      aria-label={t('shell.close_menu')}
      onclick={() => (menuOpen = false)}
    ></button>
  {/if}
{/if}

<style>
  .auth-loading {
    display: flex;
    justify-content: center;
    padding: var(--kg-space-09);
    color: var(--kg-text-secondary);
  }
  .hint {
    color: var(--kg-text-secondary);
    margin: 0;
  }
  .user-menu {
    margin-inline-start: auto;
    display: flex;
    align-items: center;
    gap: var(--kg-space-04);
    font-size: 0.875rem;
  }
  .user-name {
    color: var(--kg-shell-text);
    font-weight: 400;
  }
  .admin-badge {
    background: var(--kg-shell-hover);
    color: var(--kg-shell-text-muted);
    font-size: 0.6875rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.32px;
    padding: var(--kg-space-01) var(--kg-space-03);
  }
  .logout-btn {
    height: var(--kg-control-height-sm);
    padding: 0 var(--kg-space-05);
    border: 1px solid var(--kg-shell-border);
    background: transparent;
    color: var(--kg-shell-text);
    cursor: pointer;
    font: inherit;
    font-size: 0.875rem;
    transition: background 70ms cubic-bezier(0.2, 0, 0.38, 0.9);
  }
  .logout-btn:hover {
    background: var(--kg-shell-hover);
  }
  .logout-btn:focus-visible {
    outline: 2px solid var(--kg-primary);
    outline-offset: -2px;
  }
</style>
