// apps/inventory/lib/ModelWorkspace.tsx
import { createSignal, Show, type JSX } from 'solid-js'
import {
  Card,
  KAppStatus,
  KForm,
  KTable,
  PageHeader,
  parseNamespace,
  t,
} from '@kaizengo/sdk-solid/ui'
import { renderInventoryField } from './form-field'

type Props = {
  model: string
  title: string
  subtitle?: string
  emptyKey?: string
  formTitle?: string
  deletable?: boolean
  showForm?: boolean
}

export function ModelWorkspace(props: Props): JSX.Element {
  const [refreshToken, setRefreshToken] = createSignal(0)
  const ns = () => parseNamespace(props.model)
  const showForm = () => props.showForm ?? true
  const deletable = () => props.deletable ?? true

  return (
    <>
      <PageHeader title={props.title} subtitle={props.subtitle} />
      <div class="flex flex-col gap-5 [&_.composer]:flex-col [&_.composer]:items-stretch">
        <Show when={showForm()}>
          <Card title={props.formTitle || t('inventory.form.new')}>
            <KForm
              model={props.model}
              onsuccess={() => setRefreshToken((n) => n + 1)}
              field={(ctx) => renderInventoryField(ctx, ns().name, ns().app)}
            />
          </Card>
        </Show>
        <KTable
          model={props.model}
          emptyMessage={t(props.emptyKey ?? 'inventory.empty')}
          deletable={deletable()}
          refreshToken={refreshToken()}
        />
      </div>
      <KAppStatus />
    </>
  )
}

// apps/inventory/lib/ModelWorkspace.svelte
<script lang="ts">
  import {
    Card,
    FormField,
    KAppStatus,
    KForm,
    KTable,
    PageHeader,
    Select,
    parseNamespace,
    t,
    type KFormFieldContext,
  } from '@kaizengo/sdk-svelte/ui'
  import { ENUMS, enumKey } from './enums'
  import RelationPicker from './RelationPicker.svelte'

  type Props = {
    model: string
    title: string
    subtitle?: string
    emptyKey?: string
    formTitle?: string
    deletable?: boolean
    showForm?: boolean
  }

  let {
    model,
    title,
    subtitle = '',
    emptyKey = 'inventory.empty',
    formTitle = '',
    deletable = true,
    showForm = true,
  }: Props = $props()

  let table = $state<{ refresh: () => Promise<void> }>()
  const ns = $derived(parseNamespace(model))

  function enumOptions(fieldKey: string) {
    const values = ENUMS[enumKey(model, fieldKey)] ?? []
    return values.map((value) => {
      const key = `inventory.enum.${enumKey(model, fieldKey)}.${value}`
      const label = t(key)
      return { value, label: label === key ? value.replaceAll('_', ' ') : label }
    })
  }
</script>

<PageHeader {title} {subtitle} />

<div class="workspace">
  {#if showForm}
    <Card title={formTitle || t('inventory.form.new')}>
    <KForm {model} onsuccess={() => void table?.refresh()}>
      {#snippet field(ctx: KFormFieldContext)}
        {@const enums = enumOptions(ctx.field.key)}
        {#if ctx.field.relation}
          <FormField label={ctx.label} required={ctx.field.required}>
            <RelationPicker
              relation={ctx.field.relation}
              fromApp={ns.app}
              value={String(ctx.draft[ctx.field.key] ?? '')}
              placeholder={ctx.placeholder}
              onchange={(id) => ctx.setValue(id)}
            />
          </FormField>
        {:else if enums.length}
          <FormField label={ctx.label} required={ctx.field.required}>
            <Select
              value={String(ctx.draft[ctx.field.key] ?? '')}
              options={enums}
              onchange={(e) => ctx.setValue((e.currentTarget as HTMLSelectElement).value)}
            />
          </FormField>
        {:else}
          {@render ctx.default()}
        {/if}
      {/snippet}
    </KForm>
    </Card>
  {/if}

  <KTable bind:this={table} {model} emptyMessage={t(emptyKey)} {deletable} />
</div>

<KAppStatus />

<style>
  .workspace {
    display: flex;
    flex-direction: column;
    gap: 1.25rem;
  }
  .workspace :global(.composer) {
    flex-direction: column;
    align-items: stretch;
  }
</style>
