// packages/sdk-solid/ui/src/lib/Page.tsx
import { type JSX, type ParentProps } from 'solid-js'
import type { ThemeId } from './theme'

type Props = ParentProps & {
  theme?: ThemeId
}

export function Page(props: Props): JSX.Element {
  return (
    <div class="kg-page kg-app flex min-h-screen w-full flex-col bg-[var(--kg-bg)]" data-kg-theme={props.theme}>
      {props.children}
    </div>
  )
}

// packages/sdk-svelte/ui/src/lib/Page.svelte
<script lang="ts">
  import type { ThemeId } from './theme'

  type Props = {
    theme?: ThemeId
    children: import('svelte').Snippet
  }

  let { theme, children }: Props = $props()
</script>

<div class="kg-page kg-app" data-kg-theme={theme}>
  {@render children()}
</div>

<style>
  .kg-page {
    display: flex;
    flex-direction: column;
    width: 100%;
    min-height: 100vh;
    background: var(--kg-bg);
  }
</style>
