// apps/core/spa/src/components/ui/badge.tsx
import * as React from 'react'
import { cva, type VariantProps } from 'class-variance-authority'
import { cn } from '@/lib/utils'

const badgeVariants = cva('inline-flex items-center px-2 py-0.5 text-xs font-medium', {
  variants: {
    variant: {
      default: 'bg-[var(--kg-surface-muted)] text-[var(--kg-text-secondary)]',
      muted: 'bg-[var(--kg-surface-muted)] text-[var(--kg-text-muted)]',
      success: 'bg-[var(--kg-success-bg)] text-[var(--kg-success)]',
      danger: 'bg-[var(--kg-danger-bg)] text-[var(--kg-danger)]',
      warning: 'bg-[var(--kg-warning-bg)] text-[var(--kg-warning)]',
      info: 'bg-[var(--kg-info-bg)] text-[var(--kg-info)]',
    },
  },
  defaultVariants: { variant: 'default' },
})

export function Badge({
  className,
  variant,
  ...props
}: React.HTMLAttributes<HTMLSpanElement> & VariantProps<typeof badgeVariants>) {
  return <span className={cn(badgeVariants({ variant }), className)} {...props} />
}

export { badgeVariants }

// packages/sdk-solid/ui/src/lib/Badge.tsx
import { type JSX } from 'solid-js'
import { cn } from './cn'
import type { BadgeVariant } from './types'

const variants: Record<BadgeVariant, string> = {
  success: 'bg-emerald-100 text-emerald-800',
  danger: 'bg-red-100 text-red-800',
  warning: 'bg-amber-100 text-amber-900',
  muted: 'bg-zinc-100 text-zinc-600',
  info: 'bg-sky-100 text-sky-800',
}

type Props = {
  variant?: BadgeVariant
  children: JSX.Element
  class?: string
}

export function Badge(props: Props): JSX.Element {
  return (
    <span
      class={cn(
        'inline-flex items-center rounded px-2 py-0.5 text-xs font-medium',
        variants[props.variant ?? 'muted'],
        props.class,
      )}
    >
      {props.children}
    </span>
  )
}
