// packages/sdk-svelte/ui/src/lib/FormSection.svelte
<script lang="ts">
  type Props = {
    title: string
    description?: string
    children: import('svelte').Snippet
  }

  let { title, description, children }: Props = $props()
</script>

<fieldset class="kg-form-section">
  <legend class="kg-form-section-title">{title}</legend>
  {#if description}<p class="kg-form-section-desc">{description}</p>{/if}
  <div class="kg-form-section-fields">{@render children()}</div>
</fieldset>

<style>
  .kg-form-section {
    border: 0;
    margin: 0;
    padding: 0;
    display: flex;
    flex-direction: column;
    gap: var(--kg-space-05);
  }

  .kg-form-section-title {
    font-size: 0.875rem;
    font-weight: 600;
    letter-spacing: 0.16px;
    color: var(--kg-text);
    padding: 0;
  }

  .kg-form-section-desc {
    font-size: 0.875rem;
    letter-spacing: 0.16px;
    color: var(--kg-text-secondary);
  }

  .kg-form-section-fields {
    display: flex;
    flex-direction: column;
    gap: var(--kg-space-05);
  }
</style>

// packages/sdk-solid/ui/src/lib/FormSection.tsx
import { type JSX, type ParentProps } from 'solid-js'

type Props = ParentProps & {
  title: string
  description?: string
}

export function FormSection(props: Props): JSX.Element {
  return (
    <fieldset class="m-0 flex flex-col gap-5 border-0 p-0">
      <legend class="p-0 text-sm font-semibold text-[var(--kg-text)]">{props.title}</legend>
      {props.description && (
        <p class="text-sm text-[var(--kg-text-secondary)]">{props.description}</p>
      )}
      <div class="flex flex-col gap-5">{props.children}</div>
    </fieldset>
  )
}
