// packages/sdk-svelte/ui/src/lib/KAppStatus.svelte
<script lang="ts">
  import Alert from './Alert.svelte'
  import Card from './Card.svelte'
  import Spinner from './Spinner.svelte'
  import { getI18n, t } from './i18n-context'
  import { inferAppName } from './layout-context'
  import { fetchAppPing } from './model-client'

  type Props = {
    /** App id; defaults to I18nProvider / route context. */
    app?: string
    onerror?: (message: string) => void
  }

  let { app = '', onerror }: Props = $props()

  let root = $state<HTMLElement | null>(null)
  let loading = $state(true)
  let error = $state('')
  let status = $state('')

  const i18n = getI18n()
  const appName = $derived(app || i18n.app || inferAppName(root))

  async function refresh(name: string) {
    error = ''
    if (!name) {
      error = 'app context not available'
      loading = false
      return
    }
    loading = true
    try {
      status = await fetchAppPing(name)
    } catch (e) {
      error = e instanceof Error ? e.message : String(e)
      onerror?.(error)
    } finally {
      loading = false
    }
  }

  $effect(() => {
    void refresh(appName)
  })
</script>

<div bind:this={root} class="kg-kapp-status">
  {#if error}
    <Alert variant="danger">{error}</Alert>
  {:else if loading}
    <Spinner />
  {:else}
    <Card title={t(`${appName}.ping`)}>
      <p><code>{status}</code></p>
    </Card>
  {/if}
</div>

<style>
  .kg-kapp-status {
    margin-top: var(--kg-space-06);
  }
</style>

// packages/sdk-solid/ui/src/lib/KAppStatus.tsx
import { createSignal, onMount, Show, type JSX } from 'solid-js'
import { Alert } from './Alert'
import { Card } from './Card'
import { Spinner } from './Spinner'
import { t } from './i18n-context'
import { inferAppName } from './layout-context'
import { fetchAppPing } from './model-client'

type Props = {
  app?: string
  onerror?: (message: string) => void
}

export function KAppStatus(props: Props): JSX.Element {
  let root: HTMLDivElement | undefined

  const [loading, setLoading] = createSignal(true)
  const [error, setError] = createSignal('')
  const [status, setStatus] = createSignal('')

  async function refresh(name: string) {
    setError('')
    if (!name) {
      setError('app context not available')
      setLoading(false)
      return
    }
    setLoading(true)
    try {
      setStatus(await fetchAppPing(name))
    } catch (e) {
      const message = e instanceof Error ? e.message : String(e)
      setError(message)
      props.onerror?.(message)
    } finally {
      setLoading(false)
    }
  }

  onMount(() => {
    void refresh(props.app || inferAppName(root ?? null))
  })

  const appName = () => props.app || inferAppName(root ?? null)

  return (
    <div ref={root} class="mt-6">
      <Show when={error()} fallback={
        <Show when={!loading()} fallback={<Spinner />}>
          <Card title={t(`${appName()}.ping`)}>
            <p>
              <code>{status()}</code>
            </p>
          </Card>
        </Show>
      }>
        <Alert variant="danger">{error()}</Alert>
      </Show>
    </div>
  )
}
