// apps/core/spa/src/components/shell/ViewHost.tsx
import { useEffect, useMemo, useState } from 'react'
import { Progress } from '@/components/ui/progress'
import { I18nProvider } from '@/lib/I18nProvider'
import { contentAppForMenu } from '@/lib/spa-mount'
import { getMenuContext } from '@/lib/layout-context'
import type { MenuItem } from '@/lib/types'
import { resolveView } from '@/lib/views/registry'

type Props = {
  hostApp: string
  onerror?: (message: string) => void
}

export function ViewHost({ hostApp, onerror }: Props) {
  const menu = getMenuContext()
  const [reportedError, setReportedError] = useState('')

  const contentApp = useMemo(() => {
    if (menu.hasMenus && menu.selected) return contentAppForMenu(menu.selected, hostApp)
    return hostApp
  }, [menu.hasMenus, menu.selected, hostApp])

  const ViewComponent = useMemo(() => {
    if (!contentApp) return null
    const item = menu.hasMenus ? menu.selected : null
    return resolveView({
      app: contentApp,
      view: item?.view || undefined,
      component: item?.component || undefined,
    })
  }, [contentApp, menu.hasMenus, menu.selected])

  const viewMountKey = useMemo(() => {
    if (!ViewComponent) return ''
    const item = menu.hasMenus ? menu.selected : null
    return `${contentApp}::${item?.view ?? ''}::${item?.component ?? ''}`
  }, [ViewComponent, contentApp, menu.hasMenus, menu.selected])

  useEffect(() => {
    let message: string | null = null
    if (menu.error) message = menu.error
    else if (!menu.ready) message = null
    else if (menu.hasMenus && !menu.selected) message = null
    else if (!ViewComponent) message = missingViewMessage(contentApp, menu.selected)
    else message = ''

    if (message == null) return
    if (message === reportedError) return
    setReportedError(message)
    onerror?.(message)
  }, [menu.error, menu.ready, menu.hasMenus, menu.selected, ViewComponent, contentApp, reportedError, onerror])

  if (!menu.ready && !menu.error) {
    return (
      <div className="kg-view-host flex min-h-0 w-full min-w-0 flex-1 flex-col">
        <div className="flex items-center justify-center py-8" role="status" aria-label="Loading">
          <Progress indeterminate className="w-48 max-w-full" />
        </div>
      </div>
    )
  }

  return (
    <div className="kg-view-host flex min-h-0 w-full min-w-0 flex-1 flex-col">
      {viewMountKey && ViewComponent ? (
        <I18nProvider app={contentApp} key={viewMountKey}>
          <ViewComponent />
        </I18nProvider>
      ) : null}
    </div>
  )
}

function missingViewMessage(app: string, item: MenuItem | null): string {
  if (item?.component) return `No component registered for ${item.component}`
  if (item?.view) return `No view ${app}.${item.view}`
  return `No default view for app ${app}`
}

// apps/core/spa/src/lib/ViewHost.tsx
import { createEffect, createMemo, createSignal, on, Show, type Component } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { I18nProvider, Spinner, contentAppForMenu, getMenuContext } from '@kaizengo/sdk-solid/ui'
import type { MenuItem } from '@kaizengo/sdk-solid/ui'
import { resolveView } from './views/registry'

type Props = {
  hostApp: string
  onerror?: (message: string) => void
}

export function ViewHost(props: Props) {
  const menu = getMenuContext()
  const ready = () => menu.ready()
  const error = () => menu.error()
  const selected = () => menu.selected()
  const hasMenus = () => menu.hasMenus()

  const [reportedError, setReportedError] = createSignal('')

  const contentApp = createMemo(() => {
    if (hasMenus() && selected()) return contentAppForMenu(selected()!, props.hostApp)
    return props.hostApp
  })

  const ViewComponent = createMemo<Component | null>(() => {
    const app = contentApp()
    if (!app) return null
    const item = hasMenus() ? selected() : null
    return resolveView({
      app,
      view: item?.view || undefined,
      component: item?.component || undefined,
    })
  })

  const viewMountKey = createMemo(() => {
    const View = ViewComponent()
    if (!View) return ''
    const item = hasMenus() ? selected() : null
    return `${contentApp()}::${item?.view ?? ''}::${item?.component ?? ''}`
  })

  function missingViewMessage(app: string, item: MenuItem | null): string {
    if (item?.component) return `No component registered for ${item.component}`
    if (item?.view) return `No view ${app}.${item.view}`
    return `No default view for app ${app}`
  }

  createEffect(
    on(
      () => {
        const err = error()
        if (err) return err
        if (!ready()) return null
        if (hasMenus() && !selected()) return null
        const view = ViewComponent()
        return view ? '' : missingViewMessage(contentApp(), selected())
      },
      (message) => {
        if (message == null) return
        if (message === reportedError()) return
        setReportedError(message)
        props.onerror?.(message)
      },
    ),
  )

  return (
    <div class="kg-view-host flex min-h-0 w-full min-w-0 flex-1 flex-col">
      <Show when={ready() || error()} fallback={<Spinner />}>
        <Show when={viewMountKey()} keyed>
          {(_key) => (
            <I18nProvider app={contentApp()}>
              <Dynamic component={ViewComponent()!} />
            </I18nProvider>
          )}
        </Show>
      </Show>
    </div>
  )
}
