// apps/inventory/views/Planning.page.svelte
<script lang="ts">
  import ModelWorkspace from '../lib/ModelWorkspace.svelte'
  import { t } from '@kaizengo/sdk-svelte/ui'
</script>

<ModelWorkspace
  model="inventory.reorder_rule"
  title={t('inventory.planning.title')}
  subtitle={t('inventory.planning.subtitle')}
  emptyKey="inventory.empty.planning"
/>

// apps/inventory/views/Planning.page.tsx
import { ModelWorkspace } from '../lib/ModelWorkspace'
import { t } from '@kaizengo/sdk-solid/ui'

export default function Planning() {
  return (
    <ModelWorkspace
      model="inventory.reorder_rule"
      title={t('inventory.planning.title')}
      subtitle={t('inventory.planning.subtitle')}
      emptyKey="inventory.empty.planning"
    />
  )
}
