// apps/inventory/views/Returns.page.svelte
<script lang="ts">
  import ModelWorkspace from '../lib/ModelWorkspace.svelte'
  import { t } from '@kaizengo/sdk-svelte/ui'
</script>

<ModelWorkspace
  model="inventory.rma"
  title={t('inventory.returns.title')}
  subtitle={t('inventory.returns.subtitle')}
  emptyKey="inventory.empty.returns"
/>

// apps/inventory/views/Returns.page.tsx
import { ModelWorkspace } from '../lib/ModelWorkspace'
import { t } from '@kaizengo/sdk-solid/ui'

export default function Returns() {
  return (
    <ModelWorkspace
      model="inventory.rma"
      title={t('inventory.returns.title')}
      subtitle={t('inventory.returns.subtitle')}
      emptyKey="inventory.empty.returns"
    />
  )
}
