// apps/core/spa/src/components/shell/SearchBar.tsx
import { useEffect, useState } from 'react'
import { Input } from '@/components/ui/input'
import { searchQuery, type SearchHit } from '@/lib/search/client'

type Props = {
  collections?: string[]
  placeholder?: string
  debounceMs?: number
  onResults?: (hits: SearchHit[] | null) => void
  onQuery?: (q: string) => void
}

export function SearchBar({
  collections,
  placeholder = 'Search…',
  debounceMs = 300,
  onResults,
  onQuery,
}: Props) {
  const [q, setQ] = useState('')

  useEffect(() => {
    onQuery?.(q)
    if (!q.trim()) {
      onResults?.(null)
      return
    }
    const t = window.setTimeout(() => {
      void searchQuery(q, collections)
        .then((hits) => onResults?.(hits))
        .catch(() => onResults?.([]))
    }, debounceMs)
    return () => window.clearTimeout(t)
  }, [q, collections, debounceMs, onResults, onQuery])

  return (
    <Input
      value={q}
      placeholder={placeholder}
      onChange={(e) => setQ(e.target.value)}
      aria-label={placeholder}
    />
  )
}

export default SearchBar

// packages/sdk-solid/search/SearchBar.tsx
import { createSignal, type JSX } from 'solid-js'
import { Input } from '../ui/src/lib/Input'
import { searchQuery, type SearchHit } from './client'

type Props = {
  collections?: string[]
  placeholder?: string
  debounceMs?: number
  onResults?: (hits: SearchHit[] | null) => void
  onQuery?: (q: string) => void
}

export function SearchBar(props: Props): JSX.Element {
  const [value, setValue] = createSignal('')
  let timer: ReturnType<typeof setTimeout> | undefined

  async function runSearch(q: string) {
    props.onQuery?.(q)
    const trimmed = q.trim()
    if (!trimmed) {
      props.onResults?.(null)
      return
    }
    try {
      const hits = await searchQuery(trimmed, props.collections?.length ? props.collections : undefined)
      props.onResults?.(hits)
    } catch {
      props.onResults?.([])
    }
  }

  function handleInput(v: string) {
    setValue(v)
    clearTimeout(timer)
    timer = setTimeout(() => void runSearch(v), props.debounceMs ?? 300)
  }

  return (
    <Input
      value={value()}
      placeholder={props.placeholder ?? 'Search…'}
      onInput={handleInput}
    />
  )
}
